/**
 * Mac Daemon Client - HTTP client for communicating with the Mac CLI daemon.
 *
 * The Mac daemon runs on the MacBook and manages tmux sessions for Claude Code.
 * This client provides a typed interface for all daemon API endpoints.
 */

// Mac daemon URL from environment or default to mDNS hostname
const MAC_DAEMON_URL =
  process.env.MAC_DAEMON_URL || 'http://MacBook-Pro-von-Lukasz.local:3100';

export interface MacSession {
  sessionId: string;
  tmuxSession: string;
  command: string;
  status: 'running' | 'waiting_for_input' | 'finished' | 'error';
  outputBuffer: string[];
  createdAt: string;
  goal?: string;
}

export interface StartSessionResponse {
  success: boolean;
  sessionId: string;
  tmuxSession: string;
  message: string;
}

export interface SessionOutputResponse {
  success: boolean;
  sessionId: string;
  status: string;
  output: string[];
  hasMore: boolean;
}

export interface SessionInputResponse {
  success: boolean;
  message: string;
}

export interface ListSessionsResponse {
  success: boolean;
  sessions: MacSession[];
}

export interface TerminateSessionResponse {
  success: boolean;
  message: string;
}

export interface HealthResponse {
  status: string;
  uptime: number;
  sessions: number;
}

/**
 * Check if the Mac daemon is reachable.
 */
export async function checkHealth(): Promise<HealthResponse | null> {
  try {
    const res = await fetch(`${MAC_DAEMON_URL}/health`, {
      method: 'GET',
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) return null;
    return (await res.json()) as HealthResponse;
  } catch (error) {
    console.error('[MacClient] Health check failed:', error);
    return null;
  }
}

/**
 * Start a new CLI session on the Mac daemon.
 *
 * @param sessionId - Unique session ID (generated by Pi)
 * @param goal - Description of what this session should accomplish
 * @param command - CLI command to run (default: 'claude --dangerously-skip-permissions')
 */
export async function startCliSession(
  sessionId: string,
  goal: string,
  command = 'claude --dangerously-skip-permissions'
): Promise<StartSessionResponse> {
  console.log(`[MacClient] Starting session ${sessionId}: ${goal}`);
  console.log(`[MacClient] Command: ${command}`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ sessionId, goal, command }),
  });

  const data = (await res.json()) as StartSessionResponse;
  console.log(`[MacClient] Start response:`, data);
  return data;
}

/**
 * Send input to a running CLI session.
 *
 * @param sessionId - The session ID
 * @param input - Text input to send (will be followed by Enter)
 */
export async function sendCliInput(
  sessionId: string,
  input: string
): Promise<SessionInputResponse> {
  console.log(`[MacClient] Sending input to ${sessionId}: ${input.substring(0, 100)}...`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/input`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ input }),
  });

  const data = (await res.json()) as SessionInputResponse;
  console.log(`[MacClient] Input response:`, data);
  return data;
}

/**
 * Read current output from a CLI session.
 *
 * @param sessionId - The session ID
 */
export async function readCliOutput(
  sessionId: string
): Promise<SessionOutputResponse> {
  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/output`, {
    method: 'GET',
  });

  const data = (await res.json()) as SessionOutputResponse;
  // Don't log full output - too noisy
  console.log(`[MacClient] Output status: ${data.status}, lines: ${data.output?.length ?? 0}`);
  return data;
}

/**
 * List all active sessions on the Mac daemon.
 */
export async function listCliSessions(): Promise<ListSessionsResponse> {
  const res = await fetch(`${MAC_DAEMON_URL}/sessions`, {
    method: 'GET',
  });

  const data = (await res.json()) as ListSessionsResponse;
  console.log(`[MacClient] Listed ${data.sessions?.length ?? 0} sessions`);
  return data;
}

/**
 * Get details of a specific session.
 *
 * @param sessionId - The session ID
 */
export async function getSessionDetails(
  sessionId: string
): Promise<MacSession | null> {
  try {
    const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}`, {
      method: 'GET',
    });

    if (!res.ok) return null;
    return (await res.json()) as MacSession;
  } catch (error) {
    console.error(`[MacClient] Failed to get session ${sessionId}:`, error);
    return null;
  }
}

/**
 * Terminate a CLI session.
 *
 * @param sessionId - The session ID to terminate
 */
export async function terminateSession(
  sessionId: string
): Promise<TerminateSessionResponse> {
  console.log(`[MacClient] Terminating session ${sessionId}`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}`, {
    method: 'DELETE',
  });

  const data = (await res.json()) as TerminateSessionResponse;
  console.log(`[MacClient] Terminate response:`, data);
  return data;
}

/**
 * Wait for a session to complete (polling).
 *
 * @param sessionId - The session ID
 * @param timeoutMs - Maximum time to wait (default: 5 minutes)
 * @param pollIntervalMs - How often to check (default: 2 seconds)
 */
export async function waitForCompletion(
  sessionId: string,
  timeoutMs = 300_000,
  pollIntervalMs = 2000
): Promise<{ completed: boolean; output: string[]; status: string }> {
  const startTime = Date.now();
  let consecutiveUndefined = 0;
  const maxUndefinedRetries = 3;

  while (Date.now() - startTime < timeoutMs) {
    try {
      const result = await readCliOutput(sessionId);

      // Handle terminal states
      if (result.status === 'finished' || result.status === 'error') {
        return {
          completed: true,
          output: result.output ?? [],
          status: result.status,
        };
      }

      // Handle undefined/missing status - likely session doesn't exist or daemon issue
      if (!result.status) {
        consecutiveUndefined++;
        console.warn(
          `[MacClient] Received undefined status for session ${sessionId} (attempt ${consecutiveUndefined}/${maxUndefinedRetries})`
        );

        if (consecutiveUndefined >= maxUndefinedRetries) {
          console.error(
            `[MacClient] Session ${sessionId} returned undefined status ${maxUndefinedRetries} times, aborting poll`
          );
          return {
            completed: false,
            output: result.output ?? [],
            status: 'unknown',
          };
        }
      } else {
        // Reset counter on valid status
        consecutiveUndefined = 0;
      }

      // Wait before next poll
      await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
    } catch (error) {
      console.error(`[MacClient] Error polling session ${sessionId}:`, error);
      return {
        completed: false,
        output: [],
        status: 'error',
      };
    }
  }

  return {
    completed: false,
    output: [],
    status: 'timeout',
  };
}
