creation_rules:
  - path_regex: \.env$
    age: >-
      age1em03mkuwzzg4cpvhnfgtf4kvnsa9y4z89gtc47ufq25xnmeqf49q73qg8k,
      age1ewx0dpsx674c02rhkqhx2qt4z6v9lsqqv5t560f9k6t4vn2t6uas5lps4n,
      age1zwyr9j8jd05dc76pht5av34nj0nrsfuzw37686arzpkqzhy7nseqeaud7p
