/**
 * Mac Daemon Client - HTTP client for communicating with the Mac CLI daemon.
 *
 * The Mac daemon runs on the MacBook and manages tmux sessions for Claude Code.
 * This client provides a typed interface for all daemon API endpoints.
 */

// Mac daemon URL from environment or default to mDNS hostname
const MAC_DAEMON_URL =
  process.env.MAC_DAEMON_URL || 'http://MacBook-Pro-von-Lukasz.local:3100';

export interface MacSession {
  sessionId: string;
  tmuxSession: string;
  command: string;
  status: 'running' | 'waiting_for_input' | 'finished' | 'error';
  outputBuffer: string[];
  createdAt: string;
  goal?: string;
}

export interface StartSessionResponse {
  success: boolean;
  sessionId: string;
  tmuxSession: string;
  message: string;
}

export interface SessionOutputResponse {
  success: boolean;
  sessionId: string;
  status: string;
  output: string[];
  hasMore: boolean;
}

export interface SessionInputResponse {
  success: boolean;
  message: string;
}

export interface ListSessionsResponse {
  success: boolean;
  sessions: MacSession[];
}

export interface TerminateSessionResponse {
  success: boolean;
  message: string;
}

export type GuiTerminal = 'ghostty' | 'iterm2' | 'terminal';
export type WindowArrangement =
  | 'left_half'
  | 'right_half'
  | 'fullscreen'
  | 'top_half'
  | 'bottom_half'
  | 'center';

export interface GuiActionResponse {
  success: boolean;
  message: string;
}

export interface HealthResponse {
  status: string;
  uptime: number;
  sessions: number;
}

interface ApiEnvelope<T> {
  success?: boolean;
  data?: T;
  message?: string;
  error?: string;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object';
}

function getEnvelopeData<T>(raw: unknown): T | null {
  if (!isObject(raw)) return null;
  if (!('data' in raw)) return null;
  return (raw as ApiEnvelope<T>).data ?? null;
}

function getEnvelopeSuccess(raw: unknown, fallback: boolean): boolean {
  if (!isObject(raw)) return fallback;
  const success = (raw as ApiEnvelope<unknown>).success;
  return typeof success === 'boolean' ? success : fallback;
}

function getEnvelopeMessage(raw: unknown, fallback: string): string {
  if (!isObject(raw)) return fallback;
  const envelope = raw as ApiEnvelope<unknown>;
  if (typeof envelope.message === 'string' && envelope.message.length > 0) return envelope.message;
  if (typeof envelope.error === 'string' && envelope.error.length > 0) return envelope.error;
  return fallback;
}

/**
 * Check if the Mac daemon is reachable.
 */
export async function checkHealth(): Promise<HealthResponse | null> {
  try {
    const res = await fetch(`${MAC_DAEMON_URL}/health`, {
      method: 'GET',
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) return null;
    return (await res.json()) as HealthResponse;
  } catch (error) {
    console.error('[MacClient] Health check failed:', error);
    return null;
  }
}

/**
 * Start a new CLI session on the Mac daemon.
 *
 * @param sessionId - Unique session ID (generated by Pi)
 * @param goal - Description of what this session should accomplish
 * @param command - CLI command to run (default: 'claude --dangerously-skip-permissions')
 */
export async function startCliSession(
  sessionId: string,
  goal: string,
  command = 'claude --dangerously-skip-permissions'
): Promise<StartSessionResponse> {
  console.log(`[MacClient] Starting session ${sessionId}: ${goal}`);
  console.log(`[MacClient] Command: ${command}`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ sessionId, goal, command }),
  });

  const raw = (await res.json()) as unknown;
  const wrappedData = getEnvelopeData<{
    sessionId?: string;
    tmuxSession?: string;
  }>(raw);

  const success = getEnvelopeSuccess(raw, res.ok);
  const normalized: StartSessionResponse = wrappedData
    ? {
        success,
        sessionId: wrappedData.sessionId ?? sessionId,
        tmuxSession: wrappedData.tmuxSession ?? '',
        message: getEnvelopeMessage(raw, success ? 'Session gestartet.' : 'Fehler beim Starten der Session.'),
      }
    : {
        success,
        sessionId: (raw as Partial<StartSessionResponse>)?.sessionId ?? sessionId,
        tmuxSession: (raw as Partial<StartSessionResponse>)?.tmuxSession ?? '',
        message: getEnvelopeMessage(raw, success ? 'Session gestartet.' : 'Fehler beim Starten der Session.'),
      };

  console.log(`[MacClient] Start response:`, normalized);
  return normalized;
}

/**
 * Send input to a running CLI session.
 *
 * @param sessionId - The session ID
 * @param input - Text input to send (will be followed by Enter)
 */
export async function sendCliInput(
  sessionId: string,
  input: string
): Promise<SessionInputResponse> {
  console.log(`[MacClient] Sending input to ${sessionId}: ${input.substring(0, 100)}...`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/input`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ input }),
  });

  const raw = (await res.json()) as unknown;
  const normalized: SessionInputResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    message: getEnvelopeMessage(raw, res.ok ? 'Input gesendet.' : 'Fehler beim Senden von Input.'),
  };
  console.log(`[MacClient] Input response:`, normalized);
  return normalized;
}

/**
 * Read current output from a CLI session.
 *
 * @param sessionId - The session ID
 */
export async function readCliOutput(
  sessionId: string
): Promise<SessionOutputResponse> {
  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/output`, {
    method: 'GET',
  });

  const raw = (await res.json()) as unknown;
  const wrappedData = getEnvelopeData<{
    sessionId?: string;
    status?: string;
    output?: unknown;
    hasMore?: unknown;
  }>(raw);
  const source = wrappedData ?? (isObject(raw) ? raw : {});

  const data: SessionOutputResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    sessionId: typeof source.sessionId === 'string' ? source.sessionId : sessionId,
    status: typeof source.status === 'string' ? source.status : '',
    output: Array.isArray(source.output)
      ? source.output.filter((line): line is string => typeof line === 'string')
      : [],
    hasMore: Boolean(source.hasMore),
  };

  // Don't log full output - too noisy
  console.log(`[MacClient] Output status: ${data.status}, lines: ${data.output?.length ?? 0}`);
  return data;
}

/**
 * List all active sessions on the Mac daemon.
 */
export async function listCliSessions(): Promise<ListSessionsResponse> {
  const res = await fetch(`${MAC_DAEMON_URL}/sessions`, {
    method: 'GET',
  });

  const raw = (await res.json()) as unknown;
  const wrappedData = getEnvelopeData<unknown>(raw);
  const flatSessions = isObject(raw) ? raw.sessions : undefined;
  const candidate = wrappedData ?? flatSessions;
  const sessions = Array.isArray(candidate) ? (candidate as MacSession[]) : [];
  const normalized: ListSessionsResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    sessions,
  };

  console.log(`[MacClient] Listed ${normalized.sessions?.length ?? 0} sessions`);
  return normalized;
}

/**
 * Get details of a specific session.
 *
 * @param sessionId - The session ID
 */
export async function getSessionDetails(
  sessionId: string
): Promise<MacSession | null> {
  try {
    const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}`, {
      method: 'GET',
    });

  if (!res.ok) return null;
    const raw = (await res.json()) as unknown;
    const wrappedData = getEnvelopeData<MacSession>(raw);
    if (wrappedData) return wrappedData;
    if (isObject(raw) && typeof raw.sessionId === 'string') return raw as unknown as MacSession;
    return null;
  } catch (error) {
    console.error(`[MacClient] Failed to get session ${sessionId}:`, error);
    return null;
  }
}

/**
 * Terminate a CLI session.
 *
 * @param sessionId - The session ID to terminate
 */
export async function terminateSession(
  sessionId: string
): Promise<TerminateSessionResponse> {
  console.log(`[MacClient] Terminating session ${sessionId}`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}`, {
    method: 'DELETE',
  });

  const raw = (await res.json()) as unknown;
  const normalized: TerminateSessionResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    message: getEnvelopeMessage(raw, res.ok ? 'Session beendet.' : 'Fehler beim Beenden der Session.'),
  };
  console.log(`[MacClient] Terminate response:`, normalized);
  return normalized;
}

/**
 * Open a GUI terminal attached to an existing tmux session.
 */
export async function openGuiTerminal(
  sessionId: string,
  terminal: GuiTerminal = 'ghostty'
): Promise<GuiActionResponse> {
  console.log(`[MacClient] Opening ${terminal} GUI for session ${sessionId}`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/open-gui`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ terminal }),
  });

  const raw = (await res.json()) as unknown;
  const normalized: GuiActionResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    message: getEnvelopeMessage(
      raw,
      res.ok
        ? `${terminal} window opened.`
        : `Failed to open ${terminal} window.`
    ),
  };

  console.log('[MacClient] Open GUI response:', normalized);
  return normalized;
}

/**
 * Close the GUI terminal window for a tmux session.
 */
export async function closeGuiTerminal(
  sessionId: string
): Promise<GuiActionResponse> {
  console.log(`[MacClient] Closing GUI for session ${sessionId}`);

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/close-gui`, {
    method: 'POST',
  });

  const raw = (await res.json()) as unknown;
  const normalized: GuiActionResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    message: getEnvelopeMessage(
      raw,
      res.ok ? 'GUI window closed.' : 'Failed to close GUI window.'
    ),
  };

  console.log('[MacClient] Close GUI response:', normalized);
  return normalized;
}

/**
 * Arrange/resize a GUI terminal window for a tmux session.
 */
export async function arrangeWindow(
  sessionId: string,
  arrangement: WindowArrangement
): Promise<GuiActionResponse> {
  console.log(
    `[MacClient] Arranging GUI for ${sessionId} -> ${arrangement}`
  );

  const res = await fetch(`${MAC_DAEMON_URL}/sessions/${sessionId}/arrange`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ arrangement }),
  });

  const raw = (await res.json()) as unknown;
  const normalized: GuiActionResponse = {
    success: getEnvelopeSuccess(raw, res.ok),
    message: getEnvelopeMessage(
      raw,
      res.ok ? `Window arranged as ${arrangement}.` : 'Failed to arrange window.'
    ),
  };

  console.log('[MacClient] Arrange window response:', normalized);
  return normalized;
}

/**
 * Wait for a session to complete (polling).
 *
 * @param sessionId - The session ID
 * @param timeoutMs - Maximum time to wait (default: 5 minutes)
 * @param pollIntervalMs - How often to check (default: 2 seconds)
 */
export async function waitForCompletion(
  sessionId: string,
  timeoutMs = 300_000,
  pollIntervalMs = 2000
): Promise<{ completed: boolean; output: string[]; status: string }> {
  const startTime = Date.now();
  let consecutiveUndefined = 0;
  const maxUndefinedRetries = 3;

  while (Date.now() - startTime < timeoutMs) {
    try {
      const result = await readCliOutput(sessionId);

      // Handle terminal states
      if (result.status === 'finished' || result.status === 'error') {
        return {
          completed: true,
          output: result.output ?? [],
          status: result.status,
        };
      }

      // Handle undefined/missing status - likely session doesn't exist or daemon issue
      if (!result.status) {
        consecutiveUndefined++;
        console.warn(
          `[MacClient] Received undefined status for session ${sessionId} (attempt ${consecutiveUndefined}/${maxUndefinedRetries})`
        );

        if (consecutiveUndefined >= maxUndefinedRetries) {
          console.error(
            `[MacClient] Session ${sessionId} returned undefined status ${maxUndefinedRetries} times, aborting poll`
          );
          return {
            completed: false,
            output: result.output ?? [],
            status: 'unknown',
          };
        }
      } else {
        // Reset counter on valid status
        consecutiveUndefined = 0;
      }

      // Wait before next poll
      await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
    } catch (error) {
      console.error(`[MacClient] Error polling session ${sessionId}:`, error);
      return {
        completed: false,
        output: [],
        status: 'error',
      };
    }
  }

  return {
    completed: false,
    output: [],
    status: 'timeout',
  };
}
