/**
 * Voice Session - Wraps RealtimeSession with state management.
 *
 * Handles:
 * - WebSocket connection to OpenAI Realtime API
 * - State machine (idle → listening → thinking → speaking)
 * - Remote prompt configuration
 * - Greeting trigger after wake word
 * - Conversation timeout
 */

import {
  RealtimeAgent,
  RealtimeSession,
  type TransportLayerAudio,
  type RealtimeItem,
  type TransportEvent,
} from '@openai/agents/realtime';

// Type for input audio transcription completed event (not exported from SDK)
interface InputAudioTranscriptionCompletedEvent {
  type: 'conversation.item.input_audio_transcription.completed';
  item_id: string;
  transcript: string;
}

// Type for output audio transcript delta event (streaming assistant speech)
interface OutputAudioTranscriptDeltaEvent {
  type: 'response.output_audio_transcript.delta';
  event_id: string;
  item_id: string;
  content_index: number;
  delta: string;
  output_index: number;
  response_id: string;
}

// Type for conversation.item.added event (item created, but may not have transcript yet)
interface ConversationItemAddedEvent {
  type: 'conversation.item.added';
  event_id: string;
  previous_item_id: string | null;
  item: {
    id: string;
    type: string;
    role?: 'user' | 'assistant' | 'system';
    status?: string;
    content?: unknown[];
  };
}
import { config } from '../config.js';
import type { AgentProfile } from '../agent/profiles.js';

// Stop words that end the conversation and return to wakeword mode
const STOP_PHRASES = [
  'das wäre alles',
  'das war alles',
  "das wär's",
  'das wärs',
  'danke das wars',
  'danke das wärs',
  'tschüss',
  'auf wiedersehen',
  'bis später',
  'gute nacht',
];

function containsStopPhrase(text: string): boolean {
  const normalized = text.toLowerCase().trim();
  return STOP_PHRASES.some((phrase) => normalized.includes(phrase));
}

export type AgentState = 'idle' | 'listening' | 'thinking' | 'speaking';

export interface SessionEvents {
  stateChange: (state: AgentState) => void;
  audio: (audio: TransportLayerAudio) => void;
  audioInterrupted: () => void;
  transcript: (text: string, role: 'user' | 'assistant', itemId?: string) => void;
  transcriptDelta: (delta: string, role: 'user' | 'assistant', itemId?: string) => void;
  // Placeholder events for message ordering (emitted when item is created, before transcript)
  userItemCreated: (itemId: string) => void;
  assistantItemCreated: (itemId: string, previousItemId?: string) => void;
  historyUpdated: (history: RealtimeItem[]) => void;
  error: (error: Error) => void;
  connected: () => void;
  disconnected: () => void;
  toolStart: (name: string, args: Record<string, unknown>) => void;
  toolEnd: (name: string, result: string) => void;
}

export class VoiceSession {
  private readonly id: string;
  private session: RealtimeSession | null = null;
  private agent: RealtimeAgent;
  private profile: AgentProfile;
  private state: AgentState = 'idle';
  private eventHandlers: Partial<SessionEvents> = {};
  private conversationTimeoutId: ReturnType<typeof setTimeout> | null = null;

  // Audio buffer for chunks received before connection is ready
  private audioBuffer: ArrayBuffer[] = [];
  // Start in "buffering" mode - audio will be buffered until connect() completes
  private isConnecting = true;
  private static readonly MAX_BUFFER_SIZE = 50; // ~5 seconds at 100ms chunks
  // Track disconnection to suppress expected errors during shutdown
  private isDisconnecting = false;

  /**
   * Create a VoiceSession.
   * @param agent - The RealtimeAgent instance
   * @param profile - The agent profile configuration
   * @param sessionId - The unique session ID (generated by VoiceAgent orchestrator)
   */
  constructor(agent: RealtimeAgent, profile: AgentProfile, sessionId: string) {
    this.id = sessionId;
    this.agent = agent;
    this.profile = profile;
  }

  /**
   * Get the unique session ID for this voice session.
   * Used for parent-child session tracking.
   */
  getId(): string {
    return this.id;
  }

  on<K extends keyof SessionEvents>(event: K, handler: SessionEvents[K]): void {
    this.eventHandlers[event] = handler;
  }

  private emit<K extends keyof SessionEvents>(
    event: K,
    ...args: Parameters<SessionEvents[K]>
  ): void {
    const handler = this.eventHandlers[event];
    if (handler) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (handler as (...a: any[]) => void)(...args);
    }
  }

  private setState(newState: AgentState): void {
    if (this.state !== newState) {
      this.state = newState;
      this.emit('stateChange', newState);
    }
  }

  getState(): AgentState {
    return this.state;
  }

  async connect(): Promise<void> {
    if (this.session) {
      console.warn('Session already connected');
      return;
    }

    // Note: isConnecting is already true from constructor to buffer early audio

    // Build session config
    const sessionConfig: Record<string, unknown> = {
      inputAudioFormat: config.audio.format,
      outputAudioFormat: config.audio.format,
      voice: this.profile.voice,
      inputAudioTranscription: {
        model: 'gpt-4o-mini-transcribe',
        language: 'de',
      },
      turnDetection: {
        type: 'semantic_vad',
      },
    };

    this.session = new RealtimeSession(this.agent, {
      apiKey: config.openai.apiKey,
      transport: 'websocket',
      model: config.agent.model,
      config: sessionConfig,
    });

    this.setupEventListeners();

    try {
      await this.session.connect({
        apiKey: config.openai.apiKey,
      });
      this.isConnecting = false;
      this.setState('listening');
      this.emit('connected');
      this.resetConversationTimeout();

      // Session ID is now injected via the developer_session tool factory
      // No need to pollute conversation context with [SESSION_ID: ...]
      console.log(`[Session] Connected with ID: ${this.id}`);

      // Send greeting trigger BEFORE flushing audio buffer
      // This ensures the model greets first, then processes any buffered user speech
      if (this.profile.greetingTrigger) {
        console.log(`[Session] Sending greeting trigger for ${this.profile.name}`);
        this.session.sendMessage(this.profile.greetingTrigger);
      }

      // Now flush any buffered audio that was received during connection
      this.flushAudioBuffer();
    } catch (error) {
      this.isConnecting = false;
      this.audioBuffer = []; // Clear buffer on error
      this.emit('error', error as Error);
      throw error;
    }
  }

  private setupEventListeners(): void {
    if (!this.session) return;

    // Audio output from the agent
    this.session.on('audio', (audio: TransportLayerAudio) => {
      this.setState('speaking');
      this.emit('audio', audio);
    });

    // When audio playback is interrupted (user speaks over agent)
    // The SDK handles server-side truncation automatically.
    // We emit audioInterrupted so VoiceAgent can stop local audio playback.
    this.session.on('audio_interrupted', () => {
      this.setState('listening');
      this.emit('audioInterrupted');
    });

    // Agent starts working
    this.session.on('agent_start', () => {
      this.setState('thinking');
    });

    // Agent finished responding - includes the transcript
    this.session.on('agent_end', (_ctx, _agent, textOutput) => {
      if (textOutput) {
        this.emit('transcript', textOutput, 'assistant');
      }
    });

    // Agent tool execution
    this.session.on('agent_tool_start', (_ctx, _agent, tool, details) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const args = (details as any)?.toolCall?.arguments;
      let parsedArgs: Record<string, unknown> = {};
      try {
        parsedArgs = args ? JSON.parse(args) : {};
      } catch {
        parsedArgs = { raw: args };
      }
      // Format parameters nicely
      const paramStr = Object.entries(parsedArgs)
        .map(([k, v]) => `${k}=${JSON.stringify(v)}`)
        .join(', ');
      console.log(`[Tool] ${tool.name}(${paramStr})`);
      this.setState('thinking');
      this.emit('toolStart', tool.name, parsedArgs);
    });

    this.session.on('agent_tool_end', (_ctx, _agent, tool, result) => {
      // Truncate long results for cleaner logs
      const displayResult = result.length > 200 ? result.substring(0, 200) + '...' : result;
      console.log(`[Tool] ${tool.name} returned: ${displayResult}`);
      this.emit('toolEnd', tool.name, result);
    });

    // Tool approval - auto-approve all tools
    this.session.on('tool_approval_requested', (_ctx, _agent, approval) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const approvalAny = approval as any;
      console.log(`[Tool] Auto-approving: ${approvalAny.tool?.name || 'unknown'}`);
      // Auto-approve by calling approve on the approval item
      if (approvalAny.approvalItem?.approve) {
        approvalAny.approvalItem.approve();
      }
    });

    // Conversation history updates
    this.session.on('history_updated', (history: RealtimeItem[]) => {
      this.emit('historyUpdated', history);
      this.resetConversationTimeout();
    });

    // Transport events for transcription
    this.session.on('transport_event', (event: TransportEvent) => {
      // Detect user interruption: VAD detected speech
      // OpenAI sends input_audio_buffer.speech_started when user starts talking
      // Always emit audioInterrupted to stop any buffered audio on the frontend
      // (Don't check state - audio_stopped event may have already changed it due to race condition)
      if (event.type === 'input_audio_buffer.speech_started') {
        console.log('[VoiceSession] User speech detected - stopping playback');
        this.emit('audioInterrupted');
        this.setState('listening');
      }

      // Item added - emit placeholder before transcript arrives
      // This ensures correct message ordering in the UI
      if (event.type === 'conversation.item.added') {
        const itemEvent = event as ConversationItemAddedEvent;
        const { item, previous_item_id } = itemEvent;

        // Only create placeholder for user audio messages (not text messages like greeting trigger)
        // Audio items have content with type 'input_audio', text items have 'input_text'
        const contentArray = item.content as Array<{ type?: string }> | undefined;
        const hasAudioContent = Array.isArray(contentArray) &&
          contentArray.some((c) => c.type === 'input_audio');

        if (item.role === 'user' && item.type === 'message' && hasAudioContent) {
          this.emit('userItemCreated', item.id);
        } else if (item.role === 'assistant' && item.type === 'message') {
          this.emit('assistantItemCreated', item.id, previous_item_id ?? undefined);
        }
      }

      // Streaming assistant transcript delta
      if (event.type === 'response.output_audio_transcript.delta') {
        const deltaEvent = event as OutputAudioTranscriptDeltaEvent;
        if (deltaEvent.delta) {
          this.emit('transcriptDelta', deltaEvent.delta, 'assistant', deltaEvent.item_id);
        }
      }

      // User input audio transcription completed (always arrives complete, not streamed)
      if (event.type === 'conversation.item.input_audio_transcription.completed') {
        const transcriptEvent = event as InputAudioTranscriptionCompletedEvent;
        if (transcriptEvent.transcript) {
          this.emit('transcript', transcriptEvent.transcript, 'user', transcriptEvent.item_id);

          // Check for stop phrases to end conversation
          if (containsStopPhrase(transcriptEvent.transcript)) {
            console.log('[Session] Stop phrase detected - ending conversation');
            // Disconnect after a short delay to let the agent respond
            setTimeout(() => {
              this.disconnect();
            }, 3000);
          }
        }
      }
    });

    // Audio stopped - back to listening
    this.session.on('audio_stopped', () => {
      this.setState('listening');
    });

    // Error handling
    this.session.on('error', (errorEvent) => {
      const error =
        errorEvent.error instanceof Error ? errorEvent.error : new Error(String(errorEvent.error));

      // Suppress expected errors during disconnection (e.g., tool trying to send result after close)
      if (this.isDisconnecting) {
        console.log('[Session] Suppressed error during disconnect:', error.message);
        return;
      }

      console.error('[Session] Error:', error.message);
      this.emit('error', error);
    });
  }


  private resetConversationTimeout(): void {
    if (this.conversationTimeoutId) {
      clearTimeout(this.conversationTimeoutId);
    }
    this.conversationTimeoutId = setTimeout(() => {
      console.log('Conversation timeout - disconnecting');
      this.disconnect();
    }, config.agent.conversationTimeout);
  }

  sendAudio(audio: ArrayBuffer): void {
    // If connecting, buffer the audio for later
    if (this.isConnecting) {
      if (this.audioBuffer.length < VoiceSession.MAX_BUFFER_SIZE) {
        this.audioBuffer.push(audio);
      }
      // Silently drop if buffer is full (prevent memory issues)
      return;
    }

    if (!this.session) {
      console.warn('Cannot send audio: session not connected');
      return;
    }
    this.session.sendAudio(audio);
    this.resetConversationTimeout();
  }

  /**
   * Flush any buffered audio that was received during connection.
   */
  private flushAudioBuffer(): void {
    if (this.audioBuffer.length === 0) return;

    console.log(`[Session] Flushing ${this.audioBuffer.length} buffered audio chunks`);

    for (const chunk of this.audioBuffer) {
      if (this.session) {
        this.session.sendAudio(chunk);
      }
    }

    this.audioBuffer = [];
  }

  sendMessage(text: string): void {
    if (!this.session) {
      console.warn('Cannot send message: session not connected');
      return;
    }
    this.session.sendMessage(text);
    this.resetConversationTimeout();
  }

  interrupt(): void {
    if (!this.session) {
      return;
    }
    this.session.interrupt();
    this.setState('listening');
  }

  getHistory(): RealtimeItem[] {
    return this.session?.history ?? [];
  }

  disconnect(): void {
    if (this.conversationTimeoutId) {
      clearTimeout(this.conversationTimeoutId);
      this.conversationTimeoutId = null;
    }

    // Mark as disconnecting to suppress expected errors from pending tool calls
    this.isDisconnecting = true;

    if (this.session) {
      this.session.close();
      this.session = null;
    }

    // Clear state
    this.isConnecting = false;
    this.audioBuffer = [];

    this.setState('idle');
    this.emit('disconnected');
  }

  isConnected(): boolean {
    return this.session !== null;
  }
}
