/**
 * Sessions Repository
 *
 * Unified CRUD operations for voice sessions, subagents, and terminals.
 * All session types are persisted with parent-child relationships.
 */

import type Database from 'better-sqlite3';
import { getDatabase, generateId } from '../database.js';

export type SessionStatus =
  | 'pending'
  | 'running'
  | 'waiting_for_input'
  | 'finished'
  | 'error'
  | 'cancelled';

export type SessionType = 'voice' | 'subagent' | 'terminal';

/** @deprecated Use 'subagent' instead */
export type OrchestratorType = 'orchestrator';

export type AgentName = 'cli' | 'web_search' | 'deep_thinking';

export type VoiceProfile = 'jarvis' | 'marvin';

export interface Session {
  id: string;
  type: SessionType;
  goal: string;
  status: SessionStatus;
  // Hierarchy
  parent_id: string | null;
  // Voice-specific
  profile: VoiceProfile | null; // 'jarvis' | 'marvin' - for voice sessions
  // Subagent-specific (formerly orchestrator)
  agent_name: AgentName | null;
  model: string | null;
  conversation_history: string | null; // JSON array
  background: boolean; // true = detached/fire-and-forget, doesn't block voice agent
  // Terminal-specific
  mac_session_id: string | null;
  tool_call_id: string | null; // Links to the tool call that created this session
  // Timestamps
  created_at: string;
  updated_at: string;
  finished_at: string | null;
}

/** @deprecated Use Session instead */
export type CliSession = Session;

export interface CreateVoiceInput {
  id: string; // Voice session ID is generated by VoiceAgent
  profile: VoiceProfile;
  goal?: string; // Optional goal, defaults to "Voice conversation"
}

export interface CreateSubagentInput {
  id?: string;
  goal: string;
  agent_name: AgentName;
  model: string;
  parent_id?: string; // Voice session ID - links subagent to voice session
}

/** @deprecated Use CreateSubagentInput instead */
export interface CreateOrchestratorInput {
  id?: string;
  goal: string;
  agent_name: AgentName;
  model: string;
  parent_id?: string;
}

export interface CreateTerminalInput {
  id?: string;
  goal: string;
  parent_id: string; // Terminals must have a subagent parent
  mac_session_id?: string;
  tool_call_id?: string; // Links to the tool call that created this session
}

/** @deprecated Use CreateOrchestratorInput or CreateTerminalInput instead */
export interface CreateSessionInput {
  goal: string;
  id?: string;
  parent_id?: string;
  thread_id?: string;
}

/**
 * Session tree node for UI rendering
 */
export interface SessionTreeNode {
  id: string;
  type: SessionType;
  status: SessionStatus;
  goal: string;
  profile: VoiceProfile | null; // For voice sessions
  agent_name: AgentName | null; // For subagent sessions
  tool_call_id: string | null; // For terminals: links to the tool call that created them
  created_at: string;
  children: SessionTreeNode[];
}

export class CliSessionsRepository {
  private db: Database.Database;

  constructor(db?: Database.Database) {
    this.db = db ?? getDatabase();
  }

  // ============================================================================
  // CREATE METHODS
  // ============================================================================

  /**
   * Create a new voice session (persisted root of session tree).
   * Voice sessions are the root of all subagent and terminal sessions.
   */
  createVoice(input: CreateVoiceInput): Session {
    const now = new Date().toISOString();
    const goal = input.goal ?? `Voice conversation (${input.profile})`;

    this.db
      .prepare(
        `INSERT INTO cli_sessions
         (id, type, goal, status, profile, created_at, updated_at)
         VALUES (?, 'voice', ?, 'running', ?, ?, ?)`
      )
      .run(input.id, goal, input.profile, now, now);

    return this.findById(input.id)!;
  }

  /**
   * Create a new subagent session (stateful LLM agent).
   * Subagents are typically children of voice sessions.
   */
  createSubagent(input: CreateSubagentInput): Session {
    const id = input.id ?? generateId();
    const now = new Date().toISOString();

    this.db
      .prepare(
        `INSERT INTO cli_sessions
         (id, type, goal, status, parent_id, agent_name, model, conversation_history, created_at, updated_at)
         VALUES (?, 'subagent', ?, 'running', ?, ?, ?, '[]', ?, ?)`
      )
      .run(id, input.goal, input.parent_id ?? null, input.agent_name, input.model, now, now);

    return this.findById(id)!;
  }

  /**
   * @deprecated Use createSubagent instead.
   */
  createOrchestrator(input: CreateOrchestratorInput): Session {
    return this.createSubagent(input);
  }

  /**
   * Create a new terminal session (Claude Code CLI).
   */
  createTerminal(input: CreateTerminalInput): Session {
    const id = input.id ?? generateId();
    const now = new Date().toISOString();

    this.db
      .prepare(
        `INSERT INTO cli_sessions
         (id, type, goal, status, parent_id, mac_session_id, tool_call_id, created_at, updated_at)
         VALUES (?, 'terminal', ?, 'running', ?, ?, ?, ?, ?)`
      )
      .run(
        id,
        input.goal,
        input.parent_id,
        input.mac_session_id ?? null,
        input.tool_call_id ?? null,
        now,
        now
      );

    return this.findById(id)!;
  }

  /**
   * @deprecated Use createOrchestrator or createTerminal instead.
   */
  create(input: CreateSessionInput): Session {
    const id = input.id ?? generateId();
    const now = new Date().toISOString();

    this.db
      .prepare(
        `INSERT INTO cli_sessions (id, type, goal, status, parent_id, thread_id, created_at, updated_at)
         VALUES (?, 'terminal', ?, 'pending', ?, ?, ?, ?)`
      )
      .run(id, input.goal, input.parent_id ?? null, input.thread_id ?? null, now, now);

    return this.findById(id)!;
  }

  // ============================================================================
  // READ METHODS
  // ============================================================================

  /**
   * Find a session by ID.
   */
  findById(id: string): Session | null {
    return (
      (this.db.prepare('SELECT * FROM cli_sessions WHERE id = ?').get(id) as Session) ?? null
    );
  }

  /**
   * Find a running voice session by profile name.
   * Used to get the current voice session for parent tracking.
   */
  findRunningVoice(profile?: VoiceProfile): Session | null {
    if (profile) {
      return (
        (this.db
          .prepare(
            `SELECT * FROM cli_sessions
             WHERE type = 'voice'
             AND profile = ?
             AND status = 'running'
             ORDER BY created_at DESC
             LIMIT 1`
          )
          .get(profile) as Session) ?? null
      );
    }

    // Find any running voice session
    return (
      (this.db
        .prepare(
          `SELECT * FROM cli_sessions
           WHERE type = 'voice'
           AND status = 'running'
           ORDER BY created_at DESC
           LIMIT 1`
        )
        .get() as Session) ?? null
    );
  }

  /**
   * Find a running subagent by agent name.
   * Used to resume existing subagents instead of creating new ones.
   *
   * @param agentName - The agent name to search for
   * @param parentId - Optional parent session ID to scope the search (e.g., voice session)
   *                   If provided, only returns subagents that are children of this parent.
   *                   If not provided, returns ANY running subagent with this name.
   */
  findRunningSubagent(agentName: AgentName, parentId?: string): Session | null {
    if (parentId) {
      // Scoped search: only find subagents belonging to this parent
      return (
        (this.db
          .prepare(
            `SELECT * FROM cli_sessions
             WHERE type = 'subagent'
             AND agent_name = ?
             AND parent_id = ?
             AND status = 'running'
             ORDER BY created_at DESC
             LIMIT 1`
          )
          .get(agentName, parentId) as Session) ?? null
      );
    }

    // Unscoped search: find any running subagent (legacy behavior)
    return (
      (this.db
        .prepare(
          `SELECT * FROM cli_sessions
           WHERE type = 'subagent'
           AND agent_name = ?
           AND status = 'running'
           ORDER BY created_at DESC
           LIMIT 1`
        )
        .get(agentName) as Session) ?? null
    );
  }

  /**
   * @deprecated Use findRunningSubagent instead.
   */
  findRunningOrchestrator(agentName: AgentName): Session | null {
    return this.findRunningSubagent(agentName);
  }

  /**
   * List all sessions, optionally filtered by status and/or type.
   */
  list(options?: { status?: SessionStatus; type?: SessionType }): Session[] {
    let query = 'SELECT * FROM cli_sessions WHERE 1=1';
    const params: (string | null)[] = [];

    if (options?.status) {
      query += ' AND status = ?';
      params.push(options.status);
    }
    if (options?.type) {
      query += ' AND type = ?';
      params.push(options.type);
    }

    query += ' ORDER BY created_at DESC';

    return this.db.prepare(query).all(...params) as Session[];
  }

  /**
   * Get active sessions (pending, running, or waiting_for_input).
   */
  getActive(): Session[] {
    return this.db
      .prepare(
        `SELECT * FROM cli_sessions
         WHERE status IN ('pending', 'running', 'waiting_for_input')
         ORDER BY created_at DESC`
      )
      .all() as Session[];
  }

  /**
   * Get all root sessions (voice or subagent with no parent) that are active OR have active descendants.
   * This ensures we can navigate to running terminals even if their parent has finished.
   */
  getActiveRoots(): Session[] {
    // Use recursive CTE to find all roots with any active descendants
    return this.db
      .prepare(
        `WITH RECURSIVE ancestry AS (
           -- Start with all active sessions
           SELECT id, parent_id FROM cli_sessions
           WHERE status IN ('pending', 'running', 'waiting_for_input')

           UNION

           -- Walk up to parents
           SELECT p.id, p.parent_id FROM cli_sessions p
           INNER JOIN ancestry a ON a.parent_id = p.id
         )
         SELECT DISTINCT r.* FROM cli_sessions r
         WHERE r.type IN ('voice', 'subagent')
         AND r.parent_id IS NULL
         AND r.id IN (SELECT id FROM ancestry)
         ORDER BY r.created_at DESC`
      )
      .all() as Session[];
  }

  /**
   * Get direct children of a session.
   */
  getChildren(parentId: string): Session[] {
    return this.db
      .prepare('SELECT * FROM cli_sessions WHERE parent_id = ? ORDER BY created_at ASC')
      .all(parentId) as Session[];
  }

  /**
   * Get running children of a session.
   */
  getRunningChildren(parentId: string): Session[] {
    return this.db
      .prepare(
        `SELECT * FROM cli_sessions
         WHERE parent_id = ?
         AND status IN ('pending', 'running', 'waiting_for_input')
         ORDER BY created_at ASC`
      )
      .all(parentId) as Session[];
  }

  /**
   * Build a tree structure starting from a root session.
   */
  getTree(rootId: string): SessionTreeNode | null {
    const session = this.findById(rootId);
    if (!session) return null;

    const buildNode = (s: Session): SessionTreeNode => {
      const children = this.getChildren(s.id);
      return {
        id: s.id,
        type: s.type,
        status: s.status,
        goal: s.goal,
        profile: s.profile,
        agent_name: s.agent_name,
        tool_call_id: s.tool_call_id,
        created_at: s.created_at,
        children: children.map(buildNode),
      };
    };

    return buildNode(session);
  }

  /**
   * Get all active trees (roots with their children).
   */
  getActiveTrees(): SessionTreeNode[] {
    const roots = this.getActiveRoots();
    return roots.map((root) => this.getTree(root.id)!).filter(Boolean);
  }

  /**
   * Get recent root sessions (for chat history persistence).
   * Returns roots from the last N hours, regardless of status.
   */
  getRecentRoots(hoursAgo: number = 24, limit: number = 50): Session[] {
    return this.db
      .prepare(
        `SELECT * FROM cli_sessions
         WHERE type IN ('voice', 'subagent')
         AND parent_id IS NULL
         AND created_at >= datetime('now', '-' || ? || ' hours')
         ORDER BY created_at DESC
         LIMIT ?`
      )
      .all(hoursAgo, limit) as Session[];
  }

  /**
   * Get recent session trees (for chat history persistence).
   * Returns all trees from the last N hours, including finished ones.
   */
  getRecentTrees(hoursAgo: number = 24, limit: number = 50): SessionTreeNode[] {
    const roots = this.getRecentRoots(hoursAgo, limit);
    return roots.map((root) => this.getTree(root.id)!).filter(Boolean);
  }

  /**
   * Get a session with its direct children.
   * @deprecated Use getTree for full hierarchy.
   */
  getWithChildren(id: string): { session: Session; children: Session[] } | null {
    const session = this.findById(id);
    if (!session) return null;

    const children = this.getChildren(id);
    return { session, children };
  }

  /**
   * Get all sessions belonging to a thread.
   * @deprecated thread_id is no longer used; use getTree instead.
   */
  getByThread(threadId: string): Session[] {
    return this.db
      .prepare('SELECT * FROM cli_sessions WHERE thread_id = ? ORDER BY created_at ASC')
      .all(threadId) as Session[];
  }

  // ============================================================================
  // UPDATE METHODS
  // ============================================================================

  /**
   * Update session fields.
   */
  update(
    id: string,
    fields: Partial<{
      status: SessionStatus;
      goal: string;
      mac_session_id: string;
      conversation_history: string;
      finished_at: string;
    }>
  ): boolean {
    const updates: string[] = [];
    const params: (string | null)[] = [];

    if (fields.status !== undefined) {
      updates.push('status = ?');
      params.push(fields.status);
    }
    if (fields.goal !== undefined) {
      updates.push('goal = ?');
      params.push(fields.goal);
    }
    if (fields.mac_session_id !== undefined) {
      updates.push('mac_session_id = ?');
      params.push(fields.mac_session_id);
    }
    if (fields.conversation_history !== undefined) {
      updates.push('conversation_history = ?');
      params.push(fields.conversation_history);
    }
    if (fields.finished_at !== undefined) {
      updates.push('finished_at = ?');
      params.push(fields.finished_at);
    }

    if (updates.length === 0) return false;

    updates.push("updated_at = datetime('now')");
    params.push(id);

    const result = this.db
      .prepare(`UPDATE cli_sessions SET ${updates.join(', ')} WHERE id = ?`)
      .run(...params);

    return result.changes > 0;
  }

  /**
   * Update session status.
   * @deprecated Use update({ status }) instead.
   */
  updateStatus(id: string, status: SessionStatus): boolean {
    return this.update(id, { status });
  }

  /**
   * Set the Mac daemon session ID.
   * @deprecated Use update({ mac_session_id }) instead.
   */
  setMacSessionId(id: string, macSessionId: string): boolean {
    return this.update(id, { mac_session_id: macSessionId });
  }

  /**
   * Append to conversation history (for subagents).
   */
  appendToHistory(id: string, messages: Array<{ role: string; content: string }>): boolean {
    const session = this.findById(id);
    if (!session || session.type !== 'subagent') return false;

    const history = JSON.parse(session.conversation_history || '[]');
    history.push(...messages);

    return this.update(id, { conversation_history: JSON.stringify(history) });
  }

  /**
   * Mark session as finished.
   */
  finish(id: string, status: 'finished' | 'cancelled' | 'error' = 'finished'): boolean {
    return this.update(id, {
      status,
      finished_at: new Date().toISOString(),
    });
  }

  // ============================================================================
  // DELETE METHODS
  // ============================================================================

  /**
   * Delete a session and its events (cascade).
   */
  delete(id: string): boolean {
    const result = this.db.prepare('DELETE FROM cli_sessions WHERE id = ?').run(id);
    return result.changes > 0;
  }

  /**
   * Delete all sessions and their events (cascade).
   * Returns the number of sessions deleted.
   */
  deleteAll(): number {
    const result = this.db.prepare('DELETE FROM cli_sessions').run();
    return result.changes;
  }

  /**
   * Cancel a session and all its descendants (cascading cancel).
   * Returns the number of sessions cancelled.
   */
  cancelTree(rootId: string): number {
    const session = this.findById(rootId);
    if (!session) return 0;

    let count = 0;

    // Recursively cancel children first
    const children = this.getChildren(rootId);
    for (const child of children) {
      count += this.cancelTree(child.id);
    }

    // Cancel this session if running
    if (['pending', 'running', 'waiting_for_input'].includes(session.status)) {
      this.finish(rootId, 'cancelled');
      count++;
    }

    return count;
  }

  /**
   * Cleanup old sessions based on retention policy.
   * - Leaf subagents/voice sessions without children: 24 hours
   * - All other finished sessions: 10 days
   */
  cleanup(): { deleted: number } {
    // Delete leaf subagents and voice sessions after 24h
    const leafResult = this.db
      .prepare(
        `DELETE FROM cli_sessions
         WHERE type IN ('subagent', 'voice')
         AND status IN ('finished', 'cancelled', 'error')
         AND id NOT IN (SELECT DISTINCT parent_id FROM cli_sessions WHERE parent_id IS NOT NULL)
         AND finished_at < datetime('now', '-24 hours')`
      )
      .run();

    // Delete all finished sessions after 10 days
    const oldResult = this.db
      .prepare(
        `DELETE FROM cli_sessions
         WHERE status IN ('finished', 'cancelled', 'error')
         AND finished_at < datetime('now', '-10 days')`
      )
      .run();

    return { deleted: leafResult.changes + oldResult.changes };
  }
}

// Also export as SessionsRepository for new code
export { CliSessionsRepository as SessionsRepository };
